Add '--weekend' class to weekday
wojtekmaj/react-calendar pull request #490
Opened 2021-02-19 16:44 UTC by fffed

Add  '--weekend' class to `weekday` so we could style it differently like on a month view for dates.

2021-02-19 16:45 UTC, fffed commented
Feel free to reject it ))

2021-04-09 14:40 UTC, Chaoste commented
Code LGTM, would also love to have that.
Right now we're using `:nth-child(6+n)` which feels hacky 😅

2022-01-19 15:11 UTC, wojtekmaj requested changes
Neat - although needs a bit more work as weekends are differently defined for Arabic and Hebrew calendars :)

2022-01-19 15:11 UTC, wojtekmaj commented on src/MonthView/Weekdays.jsx
> +    const weekdayClassName = `${className}__weekday`;
Move to line 17; there's no need to re-create this variable on every render, let alone in a loop!

2022-01-19 15:11 UTC, wojtekmaj commented on src/MonthView/Weekdays.jsx
> +        className={mergeClassNames(weekdayClassName, isWeekend(weekdayDate) && `${weekdayClassName}--weekend`)}
`calendarType` is required in `isWeekend`.

```suggestion
        className={mergeClassNames(
          weekdayClassName, 
          isWeekend(weekdayDate, calendarType) && `${weekdayClassName}--weekend`
        )}
```

2022-02-04 12:50 UTC, wojtekmaj approved these changes
Great! Thanks!

2022-02-04 12:51 UTC, merged